services:
  golang-be:
    build: "./go-be/"
    ports:
      - "8081:8080"
    #image: joonaspraks/golang-be
  golang-cli:
    build: "./go-cli"
    #image: joonaspraks/golang-cli
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  adarkroom:
    image: ryhorne/adarkroom:latest
    ports:
      - "8082:80"
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
